сделал базовый css index
htmlacademy-htmlcss/1615341-nerds-31 pull request #5
Opened 2021-06-07 22:00 UTC by mrachenko

2021-06-08 15:56 UTC, costigans requested changes
Валидатор ругается — https://validator.w3.org/nu/?doc=https%3A%2F%2Fhtmlacademy-htmlcss.github.io%2F1615341-nerds-31%2F5%2F

2021-06-08 15:56 UTC, costigans commented on product.html
Для чего эта страница?
У тебя же есть catalog.html

2021-06-08 15:56 UTC, costigans commented on index.html
> +          <label for="btn-3"></label>
Мы не делаем слайдер на CSS, интерактив только JS

2021-06-08 15:56 UTC, costigans commented on index.html
> +          <li class="about__list-item">
Один и тот же класс `about__list-item` для совершенно разных списков.
Чтобы было проще нужно их разделить.

2021-06-08 15:56 UTC, costigans commented on index.html
>          </ul>
По факту это обычный список в тексте, и его можно было бы воспроизвести как-то так:
```
ul.about_list.list
   li.list__item
   ...
```

2021-06-08 15:56 UTC, costigans commented on index.html
> +          <li class="about__list-item">
А здесь можно переименовать например так:
```
ul.about__statistics.statistics
    li.statistics__item
```

2021-06-08 15:56 UTC, costigans commented on index.html
> +            <span class="about__list-item-number">
Не нужен класс.
Задашь стиль через родителя — БЭМ и критерии допускают такую вложенность. Здесь она оправдана

2021-06-08 15:56 UTC, costigans commented on index.html
>              </span><br>
Не нужен здесь `<br>`, стилями «раскидаем» текст.

2021-06-08 15:56 UTC, costigans commented on index.html
> +        <a class="partners__list-item" href="https://htmlacademy.ru/intensive/htmlcss">
`partners__item`, или даже `partners__link`

2021-06-08 15:56 UTC, costigans commented on index.html
> +        <p class="contacts__title">NЁRDS DESIGN STUDIO</p>
«Капс» задашь в стилях

2021-06-08 15:56 UTC, costigans commented on index.html
> +        <p class="contacts__adress">
Есть специальный тег под адрес

2021-06-08 15:56 UTC, costigans commented on index.html
>        </p>
Чтобы в будущем было проще стилизовать — оберни эти параграфы в один блок div.footer__intro например

2021-06-08 15:56 UTC, costigans commented on index.html
> +          <a class="social-list__button" href="#">
Лучше элемент назвать  `item` или `link`.

2021-06-08 15:56 UTC, costigans commented on index.html
> +      </form>
Форма же может быть не одна на сайте, будешь дублировать стили?
Проще так:
```
form.fedback__form.form
    ...
    input.form__input
    textarea.form__textarea
```

2021-06-08 15:56 UTC, costigans commented on index.html
> +          <textarea class="feedback__text" id="text" name="text" placeholder="В свободной форме"></textarea>
Просто text не самое удачное имя элемента, в формах бывает текст, например с каким-то пояснением.
При редактировании стилей по textarea сразу понятно, что это поле для ввода, а вот на text придётся вспоминать.

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +}
Не описаны стили покоя и нажатия

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +}
Для user-nav тоже

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +  color: var(--basic-black);
А насыщенность шрифта совпадает с макетом?

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +  padding-right: 54px;
Неа, эти свойства не здесь :)
Либо в самом блоке button, либо в его модификаторе.

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +
Лишний перенос строки

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +
Лишний перенос строки

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +p, h1, h2, h3 {
p,
h1,
h2,
h3 {

2021-06-08 15:56 UTC, costigans commented on css/style.css
> +p, h1, h2, h3 {
Одна строка — один селектор

2021-06-08 15:56 UTC, costigans commented on index.html
>            <img src="img/logo/logo-academy.svg" width="199" height="57" alt="Логотип HtmlAcademy">
Изображение не подтягивается

2021-06-08 15:56 UTC, costigans commented on index.html
> +        <a class="contacts__tel" href="tel:+78005558628">+7 800 555-86-28</a>
Неописаны стили

2021-06-08 20:56 UTC, mrachenko commented on product.html
Болванка для продукта, тайтл не поменял просто

2021-06-08 21:18 UTC, mrachenko commented on css/style.css
> +  padding-right: 54px;
А почему не тут? в самом блоке button указано дефолтное значение (по 40 рх), в модификаторах (--red, --yellow и тд)  - только цвета. Получается в этом классе и указываются специфические padding  для этого section

2021-06-09 11:04 UTC, costigans commented on product.html
А у нас есть макет для страницы продукта?

2021-06-09 11:18 UTC, costigans commented on css/style.css
> +  padding-right: 54px;
Можешь добавить ещё модификаторы — на размер/отступы/форму/рамки/текст/etc.
Всё зависит от необходимого уровня гибкости компонентов.
Когда у тебя на сайте появится кнопка с такими же отступами снова будешь задавать эти правила уже для другого элемента? А можно просто добавить модификатор :).

Через элемент проще задавать уникальные значения по контексту нахождения в родительском блоке, внешние отступы например, либо другие особенности которые накладывает конкретная вложенность одного блока в другой.

>Миксы применяют, чтобы расположить один блок относительно другого или позиционировать элементы внутри блока.
© [БЭМ для начинающих. Очевидные и неочевидные вопросы верстки](https://medium.com/@innabelaya/%D0%B1%D1%8D%D0%BC-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%8E%D1%89%D0%B8%D1%85-%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B8-%D0%BD%D0%B5%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B8-1a21d67cf840)

2021-06-09 13:00 UTC, costigans requested changes

2021-06-24 01:17 UTC, costigans approved these changes

2021-06-24 01:17 UTC, costigans commented on index.html
> +          <a href="#slide3">Кнопка 3</a>
Только не «Кнопка», а «Слайд». Ссылка ж ведёт на слайд

2021-06-24 01:17 UTC, costigans commented on index.html
> +        <button class="form__submit button button--submit button--red" type="submit">Отправить</button>
Супер!

2021-06-24 01:17 UTC, merged