стилизация страницы каталога
htmlacademy-htmlcss/1615341-nerds-31 pull request #6
Opened 2021-06-27 14:32 UTC by mrachenko

2021-06-28 20:32 UTC, costigans requested changes

2021-06-28 20:32 UTC, costigans commented on catalog.html
>            </li>
Это отдельный список.
1 список сортирует по свойствам — цена, тип, название.
2 список сортирует по величине выбранного свойства — «от большего к меньшему» и «от меньшего к большему». Добавь этот текст в пустые ссылки и оберни в `v-h`

2021-06-28 20:32 UTC, costigans commented on catalog.html
> +          </li>
Пока у тебя просто текст, он не даёт возможность отсортировать, нужны ссылки/кнопки.

2021-06-28 20:32 UTC, costigans commented on catalog.html
> +          <li class="catalog__item catalog__item--sedona catalog-item">
Тебе не нужны модфиикаторы на карточки товаров которые задают фон.
Потому что это не декоративное изображение, а контентное — это как фото товара.
Верни их в разметку

2021-06-28 20:32 UTC, costigans commented on catalog.html
>            </li>
Слишком сложная структура стилей.
Тебе точно нужно привязываться к каталогу? Это же просто навигация по страницам, она так же может встречаться например в блоге, новостях, разделе акций и т.п.
Упрощай, представь это как отдельный независимый блок пагинации, он него и строй имена классов для элементов.

2021-06-28 20:32 UTC, costigans commented on catalog.html
> +        <img class="contacts__map-marker" src="img/map-marker.png" width="231" height="190" alt="">
А зачем карту удалил?)
+ экспортирую одно изображение (карта с маркером), а не 2 отдельных

2021-06-28 20:32 UTC, costigans commented on css/style.css
> +  height: 416px;
Старайся избегать фиксированной высоты и ширины и делать интерфейс более гибким — будет проще пройти критерий на переполнение.

2021-06-28 20:32 UTC, costigans commented on css/style.css
> +}
Следи за пустыми строками. Настрой плагин для editorconfig который «причешет» отступы за тебя

2021-06-28 20:32 UTC, costigans commented on css/style.css
> +}
Перенести в разметку :)

2021-06-28 22:14 UTC, costigans requested changes

2021-06-28 22:14 UTC, costigans commented on catalog.html
> +            <a class="pagination__button pagination__button--number button button--black button--active" href="#">1</a>
Всё ещё какая-то лапша :) Очень сложно.
Тебе нет необходимости тащить сюда блок button с его модификаторами.
Стилизуй всё через элемент `pagination__item`, его базовая стилизация — это элемент содержащий числ, первый модификатор — элемент с текстом (шире внутренние отступы), второй модификатор — индиаткор активности

2021-06-28 22:14 UTC, costigans commented on catalog.html
> +            <a class="pagination__button pagination__button--number button button--black button--active" href="#">1</a>
```
<a class="pagination__item pagination__item--active" href="#">1</a>
```

2021-06-28 22:14 UTC, costigans commented on catalog.html
> +            <a class="pagination__button pagination__button--number button button--black" href="#">2</a>
```
<a class="pagination__item" href="#">2</a>
```

2021-06-28 22:14 UTC, costigans commented on catalog.html
> +            <a class="pagination__button pagination__button--next button button--black" href="#">Следующая</a>
```
<a class="pagination__item pagination__item--wide" href="#">Следующая</a>
```

2021-06-28 22:14 UTC, costigans commented on catalog.html
> +          </div>
А изображение карты где?)

2021-06-28 22:44 UTC, mrachenko commented on catalog.html
> +          </div>
так я его фоном, а потом сверху айфрейм положу

2021-06-29 14:01 UTC, costigans commented on index.html
> +              <p class="list__title">Выполняем заказы на разработку:</p>
Серьёзно? СЕРЬЁЗНО?
У ul/ol не может быть прямых потомков никаких кроме li

2021-06-29 14:02 UTC, merged